struct feed_entry *parse_rss20(struct string *buf);  // RSS 2.0
struct feed_entry *parse_rss11(struct string *buf);  // RSS 1.1
struct feed_entry *parse_rss10(struct string *buf);  // RSS 1.0
struct feed_entry *parse_rss094(struct string *buf); // RSS 0.94
struct feed_entry *parse_rss092(struct string *buf); // RSS 0.92
struct feed_entry *parse_rss091(struct string *buf); // RSS 0.91
struct feed_entry *parse_rss090(struct string *buf); // RSS 0.90
struct feed_entry *parse_atom10(struct string *buf); // Atom 1.0
struct feed_entry *parse_atom03(struct string *buf); // Atom 0.3
struct feed_entry *parse_json11(struct string *buf); // JSON 1.1
